require File.expand_path('../../lib/rdkafka/version', __FILE__)
require "fileutils"

task :default => :clean do  
  lib_path = File.join('/','usr','lib','librdkafka.so.1')
  FileUtils.cp(lib_path, File.join(File.dirname(__FILE__), "librdkafka.so"))
end

task :clean do
  FileUtils.rm_f File.join(File.dirname(__FILE__), "librdkafka.so")
end
